<?php include 'headTemplate.php';?>
    <?php 
    $str ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent metus felis, consectetur a dui quis, tempus finibus felis. Duis vitae mi quis lacus maximus ultricies. Etiam consequat dolor id lorem maximus lacinia. Sed nec risus et justo sollicitudin suscipit. Vivamus volutpat, lorem non gravida lacinia, sem quam tristique mi, sit amet elementum tellus urna non ligula. Etiam convallis nibh est, in lacinia purus consequat id. Maecenas ullamcorper ultrices ipsum, ut elementum felis blandit quis. Cras erat felis, eleifend tincidunt laoreet non, elementum eget metus. Donec felis enim, posuere ac semper et, gravida sed augue. Aenean fermentum consectetur augue, at dignissim sapien lacinia ut. Etiam at sem nisi. Integer elementum tempor lobortis.
    Nulla lobortis feugiat porttitor. Quisque consectetur, orci vitae pharetra efficitur, odio velit fringilla arcu, sed eleifend lorem magna nec libero. In facilisis lacus vitae convallis pharetra. Nullam aliquam nibh sed nibh luctus, non venenatis ante ullamcorper. Maecenas a mauris dignissim, consectetur libero scelerisque, mollis nulla. Duis ornare viverra augue blandit fringilla. Aenean at dolor ac turpis imperdiet vulputate at nec sem. Donec pharetra quam non magna placerat, id tempor libero sagittis. Suspendisse gravida felis eget lectus pharetra, ac imperdiet dui fermentum. Aenean vel pellentesque dolor.
    Phasellus vulputate suscipit efficitur. Nulla sed interdum dolor, non rhoncus purus. Aliquam nunc nisi, interdum eu convallis vel, semper et eros. Phasellus egestas eros ut enim sollicitudin fermentum. Donec consequat vestibulum egestas. Etiam pharetra iaculis tellus sit amet varius. Nulla dapibus scelerisque purus ut blandit. Duis facilisis quam et porta blandit. Duis interdum bibendum pulvinar.
    Praesent vitae sollicitudin leo, quis placerat ex. Ut non felis in mauris pharetra venenatis eget vitae velit. Phasellus vitae justo posuere, placerat nunc at, rutrum diam. Proin rhoncus dolor nulla, ut sollicitudin arcu vestibulum sed. Integer in metus augue. Nam mattis nec arcu et porttitor. Sed condimentum eros libero, id lacinia mi lobortis non.
    Ut vel risus nec ligula mattis vestibulum vel id sem. Fusce pulvinar, nunc sed scelerisque sagittis, justo tortor interdum metus, vitae maximus massa risus vel tortor. Nullam ante lacus, faucibus et commodo nec, malesuada non mauris. Vivamus odio diam, commodo non augue ut, malesuada dignissim diam. Proin dapibus turpis eros, et ullamcorper eros fringilla eget. Nunc vulputate ex justo, quis eleifend enim molestie vitae. Donec a fermentum eros. Donec eget mauris orci. Suspendisse convallis, turpis a molestie congue, eros dui semper tortor, sed ullamcorper est augue in purus. Duis interdum, leo nec lacinia cursus, dui tortor varius mauris, eget elementum mauris quam id augue. Aenean rutrum hendrerit magna, nec sodales elit bibendum vel. Etiam aliquam metus quis viverra blandit. Duis gravida urna quis ligula iaculis, venenatis aliquet leo aliquam.";
    $dimensione= rand(16,40);
    echo "<p class='text-success' style='font-size:".$dimensione."px'>".$str."</p>";
    echo "<p class='text-primary' style='font-size:".$dimensione."px'>".strtoupper($str)."</p>";
    echo "<p class='text-danger'>La quantità di caratteri è: ".strlen($str)."</p>";
    echo "<p class='text-warning'>La quantità di parole è: ".str_word_count($str)."</p>";
    ?>
<?php include 'bottomTemplate.php';?>